name: GCP Auth Test

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Auth to Google Cloud'
        id: gcloud_auth
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: 'Read JSON key'
        run: | 
            cat ${{ steps.gcloud_auth.outputs.credentials_file_path }}
            cat ${{ steps.gcloud_auth.outputs.access_token }}
    
      - name: Authenticate to GCP
        run: gcloud auth list

      - name: List GCP projects
        run: gcloud projects list